# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   
    - uses: docker/login-action@v3.3.0
      with:     
          # Username used to log against the Docker registry
          username: lexaguilar
          # Password or personal access token used to log against the Docker registry
          password: dckr_pat_PejxSRCF6qqJJ1fjHkoXPbwGeAY
    - name: Extract version from .csproj
      run: |
            VERSION=$(grep -oP '(?<=<AssemblyVersion>).*?(?=</AssemblyVersion>)' ./FactApi/FactApi.csproj)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
  
    - name: Build Docker Image 
      run: |
        docker build -t lexaguilar/factapi:latest -f ./FactApi/dockerfile FactApi --build-arg BUILD_VERSION=$VERSION
   
    - name: Push Docker Image to Docker Hub
      run: |
          docker push lexaguilar/factapi:latest
