# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x   
    - name: Extract version from .csproj
      run: |
        $VERSION = (Select-String -Path "./FactApi/FactApi.csproj" -Pattern "<AssemblyVersion>(.*?)</AssemblyVersion>").Matches.Groups[1].Value
        $VERSION

    - name: Show extracted version
      run: echo $VERSION

    - name: Set Full Version
      shell: pwsh
      run: |
        $FULL_VERSION = "${env:VERSION}.${env:GITHUB_RUN_NUMBER}"
        echo "FULL_VERSION=$FULL_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append

    - uses: docker/login-action@v3.3.0
      with:  
          username: lexaguilar
          password: dckr_pat_PejxSRCF6qqJJ1fjHkoXPbwGeAY   
  
    - name: Build Docker Image 
      run: |
        docker build -t lexaguilar/factapi:${GITHUB_RUN_NUMBER} -f ./FactApi/dockerfile FactApi --build-arg BUILD_VERSION=${FULL_VERSION}
   
    - name: Push Docker Image to Docker Hub
      run: |
          docker push lexaguilar/factapi:${GITHUB_RUN_NUMBER}
